name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    # Forks build binaries from their tags (binaries.yml), the gem is 84codes'
    if: github.repository == '84codes/sparoid.rb'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - uses: rubygems/release-gem@v1
